# -*- coding: utf-8 -*-
"""Bertopic_Trump_DTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/tpetric7/language_models_workshop/blob/main/Bertopic_Trump_DTM.ipynb

## Topic analysis

https://maartengr.github.io/BERTopic/getting_started/topicsovertime/topicsovertime.html
"""

!pip install pandas bertopic

import re
import pandas as pd

# Prepare data
trump = pd.read_csv('https://drive.google.com/uc?export=download&id=1xRKHaP-QwACMydlDnyFPEaFdtskJuBa6')
trump.text = trump.apply(lambda row: re.sub(r"http\S+", "", row.text).lower(), 1)
trump.text = trump.apply(lambda row: " ".join(filter(lambda x:x[0]!="@", row.text.split())), 1)
trump.text = trump.apply(lambda row: " ".join(re.sub("[^a-zA-Z]+", " ", row.text).split()), 1)
trump = trump.loc[(trump.isRetweet == "f") & (trump.text != ""), :]
timestamps = trump.date.to_list()
tweets = trump.text.to_list()

from bertopic import BERTopic

topic_model = BERTopic(verbose=True)
topics, probs = topic_model.fit_transform(tweets)

topics_over_time = topic_model.topics_over_time(tweets, timestamps, nr_bins=20)

topic_model.visualize_topics_over_time(topics_over_time, top_n_topics=20)

topic_model.visualize_topics_over_time(topics_over_time, topics=[9, 10, 72, 83, 87, 91])